name: slashjob
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^10.4.0
  social_media_buttons: ^1.0.0
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.6
  firebase_messaging: ^14.9.4
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.4
  firebase_core: ^2.32.0
  firebase_storage: ^11.7.5
  fluttertoast: ^8.1.1
  persistent_bottom_nav_bar: ^5.0.2
  image_picker: ^1.1.1
  file_picker: ^8.0.3
  open_file: ^3.2.1
  toggle_switch: ^2.3.0
  flutter_pdfview: ^1.3.2
  cached_network_image: ^3.3.1
  path_provider: ^2.0.5
  http: ^1.2.1
  path: ^1.8.0
  cloud_functions: ^4.7.6
  mailer: ^6.1.0
  advance_pdf_viewer: ^2.0.0
  googleapis_auth: ^1.4.1
  firebase_app_check: ^0.2.2+7
  intl: ^0.17.0
  excel: ^2.0.4
  universal_html: ^2.0.6
  file_saver: ^0.1.1
  google_fonts: ^6.2.1
  shared_preferences: ^2.0.6

dependency_overrides:
  intl: ^0.17.0  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/jaimin.jpg
    - assets/NO_FEED.png
    - assets/slash_j0b_service_account_key.json
    - assets/slas_job.png