name: slashjob
description: "it is an platorm where anyone can fine there job "
publish_to: 'play store'

version: 1.0.1+5

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^11.3.1
  social_media_buttons: ^1.0.0
  url_launcher: ^6.1.8
  cupertino_icons: ^1.0.6
  firebase_messaging: ^15.0.3
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.1
  fluttertoast: ^8.1.1
  persistent_bottom_nav_bar: ^6.2.1
  image_picker: ^1.1.1
  file_picker: ^8.0.6
  open_file: ^3.2.1
  toggle_switch: ^2.3.0
  flutter_pdfview: ^1.3.2
  cached_network_image: ^3.3.1
  path_provider: ^2.0.5
  http: ^1.2.2
  path: ^1.8.0
  cloud_functions: ^5.0.3
  mailer: ^6.1.0
  pdfx: ^2.6.0
  googleapis_auth: ^1.4.1
  firebase_app_check: ^0.3.0+3
  intl: ^0.19.0
  excel: ^4.0.3
  syncfusion_flutter_xlsio: ^26.2.9
  universal_html: ^2.0.6
  file_saver: ^0.2.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.0.6
  

dependency_overrides:
  intl: ^0.17.0  

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/slas_job_icon.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/slas_job_icon.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/slas_job_icon.jpg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/slas_job_icon.jpg"
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/jaimin.jpg
    - assets/NO_FEED.png
    - assets/slash_j0b_service_account_key.json
    - assets/slas_job.png